<!--选择挂号日期-->
<template>
  <div>
    <datescroll :tabss="tabs" @setdoctor="setdoctor"></datescroll>

    <betterscroll class="doctor" :data="currentdoctors" >
      <ul>
        <li v-for="(doctor,index) in currentdoctors">
          <div class="doctor-img">
            <img src="" alt="">
          </div>
          <div class="doctor-introduce">
            <div class="doctor-name">{{doctor.name}}</div>
            <div class="doctor-grade">{{doctor.grade}}</div>
            <div class="doctor-skill">{{doctor.skill}}</div>
          </div>
          <div class="right">
            <div class="ritht-button">{{doctor.ticket}}</div>
          </div>
        </li>
      </ul>

    </betterscroll>
  </div>

</template>

<script>
  import datescroll from "../../../common/component/datescroll.vue"
  import betterscroll from "../../../common/component/betterscroll.vue"
  export default {
    data(){
      return{
        currentdoctors:0,
        tatalwith:0,
        tabs:[{date:"08-29",week:"星期一",doctors:[{
          name:"第一个",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"10"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"最后一个",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"30"
        }]},{date:"08-29",week:"星期一",doctors:[{
          name:"第二个",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"10"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"最后一个",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"30"
        }]},{date:"08-29",week:"星期一",doctors:[{
          name:"第一个",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"10"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"最后一个",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"30"
        }]},{date:"08-29",week:"星期一",doctors:[{
          name:"第一个",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"10"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"最后一个",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"30"
        }]},{date:"08-29",week:"星期一",doctors:[{
          name:"第一个",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"10"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"王凯",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"50"
        },{
          name:"最后一个",
          grade:"主任医生",
          skill:"呼吸道感染",
          ticket:"30"
        }]},
          {date:"08-29",week:"星期一",doctors:[{
            name:"第一个",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"10"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"最后一个",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"30"
          }]},{date:"08-29",week:"星期一",doctors:[{
            name:"第一个",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"10"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"最后一个",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"30"
          }]}
          ,{date:"08-29",week:"星期一",doctors:[{
            name:"第一个",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"10"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"最后一个",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"30"
          }]},{date:"08-29",week:"星期一",doctors:[{
            name:"第一个",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"10"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"最后一个",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"30"
          }]},{date:"08-29",week:"星期一",doctors:[{
            name:"第一个",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"10"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"最后一个",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"30"
          }]},
          {date:"08-29",week:"最后一个",doctors:[{
            name:"第十个个",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"10"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"王凯",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"50"
          },{
            name:"最后一个",
            grade:"主任医生",
            skill:"呼吸道感染",
            ticket:"30"
          }]}],

      }
    },
    components: {
      datescroll,
      betterscroll
    },
    methods:{
      setdoctor(index,docto){
        console.log("我是从子组件传过来的数据"+index);
        this.currentdoctors=docto
      }
    }

  }
</script>

<style scoped lang="less" type="text/less">
  @import "../../../common/css/variable.less";
  .doctor{
    position: absolute;
    top:60px;
    left: 0;
    bottom: 0;
    right: 0;
    background: red;
    overflow: hidden;
    li{
      height: 105px;
      background: rebeccapurple;
      .doctor-img{
        float: left;
        background: yellow;
        height: 105px;
        width: 100px;

      }
      .doctor-introduce{
        float: left;
      }
      .right{
        margin-right:50px;
        float: right;
      }
    }

  }

</style>
